export default{
    toolbar: [
        'amxbar',
        'attbar',
        'attmxbar',
        'blubar',
        'cricketbar',
        'firstlybar',
        'gioneebar',
        'lenovabar',
        'myphonebar',
        'pwgbar',
        'samsungbrbar',
        'tracfonebar',
        'verizonbar',
        'uscellbar',
        'metrobar',
        'nokiainbar',
        'timbar',
        'aonebar',
        'nokialatambar',
        'nokiamenabar'
    ],
    firstscreen: [
        'cricket', 
        'blu',
        'boost',
        'firstly',
        'metropcs',
        'pwg',
        'moment'
    ],
    minusone:[
        'cricketminus1'
    ],
    portal:[
        'amxweb',
        'attweb',
        'awweb',
        'boostweb',
        'cricketweb',
        'aoneweb',
        'magentaweb',
        'metroweb',
        'mmxweb',
        'myphoneweb',
        'nokiainweb',
        'nokiamenaweb',
        'orangeweb',
        'pwgweb',
        'sprintweb',
        'uscellweb',
        'bluweb',
        'verizonweb',
        'virginweb'
    ]

}