export default {
    widgetId: {
        name: 'widgetId',
        targets: ['outbrain_block'],
        options: [
            'JS_1',
            'JS_2',
            'JS_3',
            'JS_4',
            'JS_5',
            'JS_6',
            'JS_9',
            'JS_12',
            'JS_16',
            'JS_13',
            'JS_14',
            'JS_17',
            'JS_21',
            'JS_22',
            'JS_23',
        ]
    },
    layout:
    {
        name: 'layout',
        targets: ['fotoscape_block', 'outbrain_block'],
        options: [
            "carousel",
            "carousel-photocard",
            "daily-top",
            "deals-list",
            "edge",
            "edge-description",
            "edge-list",
            "edge-tile",
            "games-carousel",
            "games-hero",
            "games-tile",
            "large-photocard",
            "licensed",
            "list-medium",
            "list-small",
            "list-small-sponsored",
            "podcast-large",
            "podcast-small",
            "quiz-carousel",
            "quiz-hero",
            "quiz-tile",
            "slideshow",
            "small-photocard",
            "small-photocard-flat",
            "stub",
            "tile",
            "trending-carousel",
            "instant-play-games"
        ],
    },

    category:
    {
        name: 'category',
        targets: ['fotoscape_block', 'outbrain_block'],
        options: [
            "Wellness",
            "accuweather",
            "ahoramismo",
            "apnews",
            "astrology",
            "baseball",
            "best-photography",
            "blackhistorymonth",
            "bloomberg",
            "business",
            "cars",
            "celebrities",
            "celebrity-homes",
            "celebrityhomes-es",
            "engage",
            "entertainment",
            "entertainment-es-mx",
            "entrepreneur",
            "foodanddrink",
            "funny",
            "gaming",
            "gearandgadgets",
            "german",
            "german-originals",
            "german_2",
            "gift_guides",
            "golf",
            "health",
            "heavy",
            "india",
            "inexpensive_gifts",
            "latenight",
            "licensed-entertainment",
            "licensed-news",
            "licensed-sports",
            "licensed-tribunetop",
            "lifestyle",
            "lifestyle-es-mx",
            "mix",
            "mix-es",
            "news",
            "news-es-mx",
            "newspop_top_news",
            "nfl",
            "olympics",
            "originals-style",
            "outdoor_photography",
            "pets",
            "podcast",
            "quizzes",
            "recipes",
            "referral_food",
            "referral_sports",
            "referral_technology",
            "referral_test_es",
            "referral_top_five",
            "science",
            "service_link",
            "service_link_2",
            "shopping",
            "simplyrecipes",
            "skinnytaste",
            "sneakers",
            "soccer",
            "spanish-originals",
            "sponsored-att",
            "sponsored_verizon",
            "sports",
            "sports-es-mx",
            "strangenews",
            "style",
            "technology",
            "technology-es-mx",
            "test",
            "travel",
            "travel-es",
            "tribune",
            "tribune-spanish",
            "tvandfilm",
            "upi",
            "verizon-deals",
            "wellness",
            "winterolympics",
            "world",
            "family",
            "home",
            "personalfinance",
            "topfive",
            "politics",
            "topnews",
            "thanksgiving",
            "deals",
            "fitness",
            "static",
            "gifts",
            "stereogum",
            "bestof-2022",
            "bestof-tech-2022",
            "bestof-news-2022",
            "bestof-entertainment-2022",
            "bestof-lifestyle-2022",
            "bestof-Originals-2022",
            "new-years-resolutions",
            "oscars"
        ],
    },

    link_destination: {
        name: 'link_destination',
        targets: ['fotoscape_block'],
        options: [
            'fotoscape',
            'referral',
            'full_page_article'
        ],
    },
    count: {
        name: 'count',
        targets: ['fotoscape_block'],
        options: [
            1,
            2,
            3,
            4,
            5,
            6,
            7,
            8,
            9,
            10,
            11,
            12,
            13,
            14,
            15,
            16,
            17,
            18,
            19,
            20,
        ],
    },
    subheader: {
        name: 'subheader',
        targets: ['header-block'],
        options: undefined,
    }

}